### ISSUE TITLE
Automatic/manual reconnect

### ISSUE THREAD

**Issue by d-markevich** [Shcherbich/QLdapEditor#18]

**Comment by d-markevich** [comment]
Запутали вы меня :-)

Так что такое waiting for acceptance? Мною после QA или QA после разработки? Судя по логу Дмитрий только что ее в работу взял. Так может Testing а не waiting for acceptance?

**Comment by dmitry-vrachev** [comment]
@d-markevich 
>Так что такое waiting for acceptance? Мною после QA или QA после разработки?

 QA после разработки.

>Так может Testing а не waiting for acceptance?

С одной стороны - у  нас на канбан-досках такое название принято, оно привычное и не очень хочется его менять. С другой - получается, что с точки зрения текущего состояния борда вы должны акцептить таски, когда они попадают в done. Не уверен, что это удобно, давайте обсудим на демо, если хотите.

**Comment by dmitry-vrachev** [comment]
1. No automatic reconnection, connection is broken after some time.

2. Start application, wait some time until the connection is broken. Try to add a new attribute for some entity - the list of attributes is empty (because the connection is broken). Press the 'Reconnect' button. Try to add a new attribute again.
Expected - all works without any additional actions.
Actual - you need to select another entity beforehand.

**Comment by d-markevich** [comment]
Я отказался от аксепта, акцепт делает ваш QA. Я все читаю когда есть время, если мне что то не понравится верну обратно

Dmitry

**Comment by d-markevich** [comment]
А почему пропадает связь пробовали выяснить? С точки зрения сетевой среды по идее не должно, Сеть то локальная, может само приложение или сервер его закрывают? Давайте попробуем понять причину прежде чем бороться с последствиями.


Dmitry
